Traceback (most recent call last):
  File "main.py", line 77, in open_file
    output_file_df=update_output_file(output_file_df,input_file_df)
UnboundLocalError: local variable 'output_file_df' referenced before assignment
